luaDebugMode = true
function onCreate()
    if downscroll then
    makeLuaSprite('boyf', 'healthimages/'..getProperty('boyfriend.curCharacter'), 650, -50)
    setObjectCamera('boyf', 'hud')
    addLuaSprite('boyf', true)
    makeLuaSprite('drad', 'healthimages/'..getProperty('dad.curCharacter'), 75, -50)
    setObjectCamera('drad', 'hud')
    addLuaSprite('drad', true)
    makeLuaText('drad Percent', '50%', 250, 300, 55)
    setTextSize('drad Percent', 75)
    addLuaText('drad Percent')
    makeLuaText('boyf Percent', '50%', 450, 770, 55)
    setTextSize('boyf Percent', 75)
    addLuaText('boyf Percent')
    scaleObject('drad', 0.7, 0.7)
    scaleObject('boyf', 0.7, 0.7)
    setObjectCamera('drad Percent', "hud")
    setObjectCamera('boyf Percent', "hud")
    makeLuaText('misses', 'Misses: 0', 200, 15, 400)
    setObjectCamera('misses', 'hud')
    setTextSize('misses', 25)
    setTextAlignment('misses', 'left')
    addLuaText('misses')
    makeLuaText('score', 'Score: 0', 200, 15, 430)
    setObjectCamera('score', 'hud')
    setTextSize('score', 25)
    setTextAlignment('score', 'left')
    addLuaText('score')
    else
    makeLuaSprite('boyf', 'healthimages/'..getProperty('boyfriend.curCharacter'), 650, 450)
    setObjectCamera('boyf', 'hud')
    addLuaSprite('boyf', true)
    makeLuaSprite('drad', 'healthimages/'..getProperty('dad.curCharacter'), 75, 450)
    setObjectCamera('drad', 'hud')
    addLuaSprite('drad', true)
    makeLuaText('drad Percent', '50%', 250, 300, 555)
    setTextSize('drad Percent', 75)
    addLuaText('drad Percent')
    makeLuaText('boyf Percent', '50%', 450, 770, 555)
    setTextSize('boyf Percent', 75)
    addLuaText('boyf Percent')
    scaleObject('drad', 0.7, 0.7)
    scaleObject('boyf', 0.7, 0.7)
    setObjectCamera('drad Percent', "hud")
    setObjectCamera('boyf Percent', "hud")
    makeLuaText('misses', 'Misses: 0', 200, 15, 400)
    setObjectCamera('misses', 'hud')
    setTextSize('misses', 25)
    setTextAlignment('misses', 'left')
    addLuaText('misses')
    makeLuaText('score', 'Score: 0', 200, 15, 430)
    setObjectCamera('score', 'hud')
    setTextSize('score', 25)
    setTextAlignment('score', 'left')
    addLuaText('score')

end
end

function onUpdate(elapsed)
    setTextString('misses', 'Misses: '.. misses)
    setTextString('score', 'Score: '.. score)
    setProperty('healthBar.alpha', 0)
    setProperty('iconP2.alpha', 0)
    setProperty('iconP1.alpha', 0)
    setProperty('scoreTxt.alpha', 0)
    setTextString("drad Percent", math.floor(getProperty('healthBar.percent') + 0.5) .. "%")
    setTextString("boyf Percent", math.floor(100 - getProperty('healthBar.percent') + 0.5) .. "%")
end